### ISSUE TITLE
Unshort.link Feedback: reurl.cc not expand

### ISSUE THREAD

**Issue by pixiandouban** [simonfrey/unshort.link#56]
This shortlink (https://reurl.cc/Oq9lQg) can’t expand to a long link.

-----
Short Url: https://reurl.cc/Oq9lQg
Long Url: https://reurl.cc/Oq9lQg

**Comment by simonfrey** [comment]
That is due to the way how reurl.cc redirects. They do that with a javascript setup. 

```
 window.location.replace(target);
```
With target being the value of a input field.

This would be generally solved by #28 as we could than adapt to all forms of javascript dedirects. For simpler cases we could check with a regex for the url redirect schemas in javascript:
```
// Simulate a mouse click:
window.location.href = "http://www.w3schools.com";

// Simulate an HTTP redirect:
window.location.replace("http://www.w3schools.com");
```
reurl.cc can an this point in time not be supported as of the required headless chrome setup
